export const questionsEasy = [
  "Forscher entdeckten einen alten Knochen mein einem C14 Gehalt von 12%\n Berechne das Alter: \n \n",
  "Ein totes Bison liegt schon seit 40'000 Jahren im Moor \n Wie hoch ist der C14-Anteil noch ? \n \n",
  "Ein Holzstück aus einer Ausgrabung enthält nur noch 25% des ursprünglichen C14-Gehalts\nWie alt ist es?\n\n",
  "Ein alter Holzpfeil aus einer Höhle enthält noch 6% des ursprünglichen C14\nWie alt ist dieser Fund?\n\n",
  "Ein prähistorisches Musikinstrument aus Knochen hat nur noch 1,2% C14\nWie alt ist es vermutlich?\n\n",
  "Ein in Lehm konservierter Fisch zeigt 13% des ursprünglichen C14-Gehalts\nWie alt ist das Tier?\n\n",
  "Ein alter Lederschuh aus einem Gletscher weist 4,5% C14 auf\nBestimme das Alter\n\n",
  "Ein Höhlenbär-Skelett enthält noch 0,6% C14\nWie alt sind die Überreste?\n\n",
  "Ein Kleidungsstück aus Wolle zeigt 9,9% des ursprünglichen C14\nWie viele Jahre ist es alt?\n\n",
  "Ein altes Segel aus Hanf enthält nur noch 2,3% C14\nBerechne das Alter\n\n",
  "Eine Holzmaske aus einem Grab weist noch 17% C14 auf\nWie alt ist sie?\n\n",
  "Ein bronzezeitlicher Speer mit Holzschaft enthält 5,2% C14\nWie viele Jahre sind vergangen?\n\n",
  "Ein altes Schriftstück aus Papyrus enthält 20% C14\nWie alt ist es?\n\n",
  "Ein Mammutstoßzahn enthält 1,1% des ursprünglichen C14-Gehalts\nWie alt ist er?\n\n",
  "Ein im Wüstensand konservierter Teppich weist 7% C14 auf\nBerechne das Alter\n\n",
  "Ein in Eis gefundenes Reh hat noch 3,3% C14\nWie alt könnte es sein?\n\n",
  "Eine aus Holz geschnitzte Figur enthält 11% des ursprünglichen C14\nWie alt ist sie?\n\n",
  "Ein alter Apfelkern zeigt 14% C14\nWie alt ist dieser Samen?\n\n",
  "Ein in Bernstein eingeschlossenes Blatt enthält noch 0,8% C14\nWie alt ist es?\n\n",
  "Ein antikes Muschelschmuckstück weist 18% C14 auf\nWie alt könnte es sein?\n\n",
  "Eine alte Holzhütte enthält noch 2,7% C14\nBerechne ihr Alter\n\n",
  "Ein zerfallenes Boot aus Schilfrohr enthält 9,1% C14\nWie alt ist das Boot?\n\n",
  "Ein in Salz konserviertes Fleischstück zeigt 10% C14\nWie alt ist es?\n\n",
  "Ein im Moor gefundenes Moorleiche weist noch 3% C14 auf\nBerechne ihr Alter\n\n",
  "Ein prähistorischer Vogel enthält 12,2% C14\nWie alt sind seine Überreste?\n\n",
  "Ein alter Baumstamm zeigt 15% des ursprünglichen C14-Gehalts\nWie alt ist er?\n\n", //hab
  "Ein Lederbeutel aus einer Grabstätte enthält 4,8% C14\nWie viele Jahre sind vergangen?\n\n",
  "Ein altes Haus aus Holz hat 8,7% C14 in den Balken\nWie alt ist es?\n\n",
  "Ein hölzernes Floß weist 6,4% C14 auf\nBerechne sein Alter\n\n",
  "Ein zerfallener Sattel aus Tierhaut enthält 3,2% C14\nWie alt ist der Fund?\n\n",
  "Ein in Lehm vergrabener Speer zeigt 10,8% C14\nWie alt könnte er sein?\n\n",
  "Ein gefundener Kürbisrest enthält 5,9% C14\nBerechne das Alter\n\n",
  "Ein mit Feuerstein gefüllter Lederbeutel weist 7% C14 auf\nWie alt ist er?\n\n",
  "Ein Bärenfell enthält 1,9% C14\nWie alt ist es vermutlich?\n\n",
  "Ein altes Flötenstück aus Holz zeigt 3,5% C14\nWie alt ist es?\n\n",
  "Ein Tierknochen in einer Höhle enthält 2,2% C14\nBerechne das Alter\n\n",
  "Ein gefundener Bienenstock aus Lehm zeigt 6% C14\nWie alt ist er?\n\n",
  "Ein Weidenkorb enthält 9,4% C14\nWie alt ist er?\n\n",
  "Ein altes Schild aus Holz enthält 11,5% C14\nWie alt ist es?\n\n",
  "Ein antikes Holztor weist 13,3% C14 auf\nWie viele Jahre sind vergangen?\n\n",
  "Ein in einer Höhle gefundener Bogen zeigt 4,1% C14\nWie alt ist er?\n\n",
  "Ein Pflanzenrest aus einem Gletscher enthält 8,2% C14\nBerechne das Alter\n\n",
  "Ein fossiles Blatt enthält nur noch 0,9% C14\nWie alt könnte es sein?\n\n",
  "Ein verbrannter Ast aus einem Lagerfeuer enthält 3,8% C14\nWie alt ist der Fund?\n\n",
  "Ein aus Stoff bestehendes Gewand zeigt 12% C14\nWie alt könnte es sein?\n\n",
  "Ein von Lava eingeschlossenes Holzbett weist 2,5% C14 auf\nWie alt ist es?\n\n",
  "Ein Teil eines Ziegenfells enthält 6,7% C14\nBerechne das Alter\n\n",
  "Ein geschnitzter Wanderstock enthält 9% C14\nWie alt ist er?\n\n",
  "Ein aus Weide geflochtenes Fischernetz zeigt 10,1% C14\nWie viele Jahre sind vergangen?\n\n", //hab
  "Ein uraltes Seil aus Hanffasern enthält 5,5% C14\nWie alt ist es?\n\n",
  "Ein gefundenes Butterstück im Moor enthält 2% C14\nWie alt ist der Fund?\n\n",
  "Ein in Sand begrabener Schildkrötenpanzer zeigt 7,7% C14\nWie alt ist er?\n\n",
  "Ein alter Holzteller enthält 11,3% C14\nBerechne sein Alter\n\n",
  "Ein Tongefäß mit organischen Rückständen zeigt 3,4% C14\nWie alt ist es?\n\n",
  "Ein in Felsnischen gelagerter Sack mit Mais enthält 8,4% C14\nWie alt ist er?\n\n",
  "Ein alter Federkopfschmuck zeigt 5,1% des ursprünglichen C14\nWie alt könnte er sein?\n\n",
  "Ein aus Moos gefertigter Schuh enthält 9,3% C14\nWie alt ist er?\n\n",
  "Ein Jagdmesser mit Holzgriff enthält 7% C14 im Griff\nBerechne das Alter\n\n",
  "Ein Gletscherfund eines Steinzeitjägers enthält 4,2% C14\nWie alt ist er?\n\n",
  "Ein Überrest eines alten Katapults enthält 6,8% C14\nWie viele Jahre sind vergangen?\n\n",
  "Ein Kornvorrat aus einem Vorratsloch zeigt 10,6% C14\nWie alt ist er?\n\n",
  "Ein aus Palmblättern gefertigter Umhang enthält 3,9% C14\nWie alt ist er?\n\n",
  "Ein in Bernstein eingeschlossenes Insekt enthält 1,4% C14\nBerechne das Alter\n\n",
  "Ein Holzstück aus einer alten Schiffsplanke zeigt 8,9% C14\nWie alt ist es?\n\n",
  "Ein gefundener Gürtel aus Bast zeigt 5,6% C14\nWie viele Jahre sind vergangen?\n\n",
  "Ein konserviertes Vogelnest enthält 2,8% C14\nWie alt ist es?\n\n",
  "Ein eingewachsener Baumzweig in einer Ruine zeigt 7,2% C14\nWie alt könnte er sein?\n\n",
  "Ein aus Gras geflochtenes Seil zeigt 6,6% C14\nWie alt ist es?\n\n",
  "Ein alter Käfig aus Bambus zeigt 11,7% C14\nBerechne das Alter\n\n",
  "Ein verrotteter Schild aus Rinde zeigt 4,3% C14\nWie alt ist er?\n\n",
  "Ein Pfeilköcher aus Hirschleder zeigt 3,1% C14\nWie viele Jahre sind vergangen?\n\n",
  "Ein fragmentierter Knochen zeigt 5% C14\nWie alt könnte er sein?\n\n",
  "Ein zerbrochener Trinkbecher aus Holz enthält 12,9% C14\nWie alt ist er?\n\n",
  "Ein gewebter Teppich aus Wolle enthält 9,6% C14\nWie alt ist der Fund?\n\n", // hab
  "Ein zerfallenes Buch aus Pflanzenfasern enthält 8% C14\nWie alt ist es?\n\n",
  "Ein verbrannter Tischbeinrest zeigt 6,1% C14\nWie alt ist er?\n\n",
  "Ein geschnitzter Holzlöffel zeigt 2,6% C14\nWie viele Jahre sind vergangen?\n\n",
  "Ein uralter Holzrahmen enthält 4,9% C14\nWie alt ist er?\n\n",
  "Ein Moosgewebe aus einem Ritual zeigt 7,4% C14\nWie alt könnte es sein?\n\n",
  "Ein gebleichter Hirschknochen zeigt 2,1% C14\nWie viele Jahre sind vergangen?\n\n",
  "Ein Knochenkamm zeigt 3,6% des ursprünglichen C14\nWie alt ist er?\n\n",
  "Ein aus Fasern gedrehter Gürtel zeigt 6,3% C14\nWie alt könnte er sein?\n\n",
  "Ein aus Birkenrinde gefertigter Becher zeigt 10,5% C14\nWie viele Jahre sind vergangen?\n\n",
  "Ein Teil eines Einbaums zeigt 8,1% C14\nWie alt ist er?\n\n",
  "Ein uraltes Zelt aus Tierhaut enthält 9,2% C14\nWie alt könnte es sein?\n\n",
  "Ein altes Brotstück zeigt 2,4% C14\nBerechne das Alter\n\n",
  "Ein Steinzeitliches Lasso aus Gras zeigt 3,3% C14\nWie alt ist es?\n\n",
  "Ein Pfeilspitzen-Holzschaft zeigt 7,1% C14\nWie alt ist der Fund?\n\n",
  "Ein aus Bast gefertigter Kopfschmuck zeigt 6,9% C14\nWie alt ist er?\n\n",
  "Ein Fossil im Schlamm zeigt 1,7% C14\nWie viele Jahre sind vergangen?\n\n",
  "Ein alter Dolch mit Holzgriff zeigt 5,7% C14\nWie alt könnte er sein?\n\n",
  "Ein Kanu-Rest aus Ahornholz zeigt 9,8% C14\nBerechne das Alter\n\n",
];

export const questionsHard = [
  "Ein Buch aus einer antiken Bibliothek wurde auf 30 % C14 geschätzt\nNeue Messungen zeigen aber nur noch 12 % – wie viele Jahre wurden unterschätzt?\n\n",
  "Ein konservierter Mammut-Stoßzahn weist einen C14-Gehalt von 22 % auf\nEin Kollege behauptet, es seien 33 % – wie viele Jahre beträgt die Differenz?\n\n",
  "Ein alter Holzpfeiler enthält laut erster Analyse 17 % C14\nEine zweite Analyse ergibt nur 9 % – wie alt ist der Unterschied?\n\n",
  "Ein Fundstück aus einer Höhle hat laut Datierung 40 % C14\nEine neuere Methode ergibt 25 % – um wie viele Jahre unterscheiden sich die Ergebnisse?\n\n",
  "Ein prähistorisches Kleidungsstück weist 15 % C14 auf\nEin Museum hatte es ursprünglich auf 30 % geschätzt – wie viele Jahre lagen sie daneben?\n\n",
  "Ein Lederstück aus einer Gruft hat 10 % C14\nFrüher wurde von 20 % ausgegangen – wie groß ist der Zeitunterschied?\n\n",
  "Eine Holzbalkenprobe wird mit 45 % C14 angegeben\nDie korrekte Messung zeigt 18 % – wie viele Jahre beträgt die Differenz?\n\n",
  "Ein fossiler Fisch wurde auf 28 % C14 datiert\nSpäter stellt sich heraus, dass der Wert nur bei 12 % liegt – was bedeutet das zeitlich?\n\n",
  "Ein Fragment aus einer alten Statue enthält noch 21 % C14\nVorher wurde ein Gehalt von 31 % angenommen – wie alt ist die Differenz?\n\n",
  "Ein Knochen aus der Wüste hat 35 % C14\nNeue Geräte geben jedoch nur 16 % an – wie viele Jahre trennen diese Einschätzungen?\n\n",
  "Ein antikes Papyrus hat laut Scanner 19 % C14\nEin externes Labor misst nur 11 % – wie viele Jahre Differenz ergeben sich?\n\n",
  "Ein alter Pfeilkopf mit Holzschaft hat 23 % C14\nEin anderer Forscher schätzte ihn auf 36 % – um wie viele Jahre lag er falsch?\n\n",
  "Ein Fundstück aus dem Regenwald wurde auf 20 % C14 datiert\nNeuere Ergebnisse zeigen 8 % – wie alt ist der Unterschied?\n\n",
  "Ein versteinerter Palmwedel enthält 14 % C14\nZuvor wurde 27 % vermutet – was bedeutet das altersmäßig?\n\n",
  "Ein Museumsstück war mit 32 % C14 verzeichnet\nNach neuen Messungen sind es nur 14 % – wie groß ist die zeitliche Abweichung?\n\n",
  "Ein Blattabdruck aus Vulkanasche hat 40 % C14\nAktuelle Werte liegen aber bei 18 % – wie viele Jahre liegen zwischen den Annahmen?\n\n",
  "Ein bemalter Holzteller zeigt 11 % C14\nFrüher wurden 22 % angegeben – wie viel Altersunterschied ergibt sich?\n\n",
  "Ein alter Wandteppich hat 17 % C14\nEin Katalog ging von 30 % aus – wie viele Jahre Differenz entstehen?\n\n",
  "Eine Mumie weist 13 % C14 auf\nEin alter Bericht spricht von 26 % – was ist die zeitliche Abweichung?\n\n",
  "Ein Holzstück aus einem Wrack hat 16 % C14\nEin älteres Gutachten ging von 35 % aus – wie viele Jahre trennen die Einschätzungen?\n\n",
  "Ein Blatt wurde auf 5000 Jahre datiert\nWie viel Prozent C14 enthält es heute noch?\n\n",
  "Ein Knochenfragment ist laut Analyse 12000 Jahre alt\nWie hoch ist der verbliebene C14-Anteil?\n\n",
  "Ein Stück Holz aus einer Grabkammer wurde auf 25000 Jahre geschätzt\nWelcher Prozentsatz C14 ist noch enthalten?\n\n", //hab
  "Ein Tierknochen aus der Steppe ist 7000 Jahre alt\nWie viel Prozent C14 ist noch nachweisbar?\n\n",
  "Ein verkohlter Baumstamm wurde auf 43000 Jahre datiert\nWie viel C14 ist heute noch vorhanden?\n\n",
  "Ein Holzkeil aus einem Gletscher ist 3000 Jahre alt\nWelcher Prozentsatz C14 müsste noch vorhanden sein?\n\n",
  "Ein Papyrusfragment ist 1800 Jahre alt\nWie viel Prozent C14 bleibt nach dieser Zeit übrig?\n\n",
  "Ein organischer Stoff in einem Tonkrug wurde auf 8000 Jahre datiert\nWie viel Prozent C14 enthält er noch?\n\n",
  "Ein Stück Leder aus einer Höhle ist 16000 Jahre alt\nWie viel C14 ist noch vorhanden?\n\n",
  "Ein versteinertes Blatt ist 20000 Jahre alt\nWelcher Anteil des ursprünglichen C14 ist noch da?\n\n",
  "Ein Pfeilschaft wurde auf 9500 Jahre bestimmt\nWie viel Prozent C14 könnte man noch messen?\n\n",
  "Ein Holzstück aus einem Moor ist 6000 Jahre alt\nWelcher Prozentsatz C14 bleibt übrig?\n\n",
  "Ein Schädelknochen wurde auf 10000 Jahre datiert\nWie viel C14 dürfte noch enthalten sein?\n\n",
  "Ein gefundener Zahn ist 22000 Jahre alt\nWie viel Prozent C14 ist nachweisbar?\n\n",
  "Ein Bogen aus einem Grab wurde auf 14000 Jahre geschätzt\nWie viel Prozent C14 hat er noch?\n\n",
  "Ein Stofffetzen aus einer antiken Kleidung wurde auf 3500 Jahre datiert\nWie viel C14 ist noch enthalten?\n\n",
  "Ein Fund aus einem Seeufer ist 27000 Jahre alt\nWie viel Prozent C14 bleibt nach so langer Zeit übrig?\n\n",
  "Ein Fischskelett ist 18000 Jahre alt\nWie hoch ist der verbleibende Anteil an C14?\n\n",
  "Ein Stück Kohle wird auf 2000 Jahre geschätzt\nWie viel Prozent des C14 ist noch vorhanden?\n\n",
  "Ein Baumstamm wurde mit 52000 Jahren Alter bestimmt\nWie viel C14 enthält er noch?\n\n",
  "Ein Holzwurzelrest ist 15000 Jahre alt\nWie viel Prozent C14 kann man heute noch messen?\n\n",
  "Ein Knochen ist 2500 Jahre alt\nWelcher Anteil des C14 ist noch vorhanden?\n\n", //hab
  "Ein Tierfell in einer Höhle wurde auf 4300 Jahre geschätzt\nWie viel Prozent C14 bleibt?\n\n",
  "Ein Holzbalken in einer Ruine ist 10500 Jahre alt\nWie viel C14 enthält er heute noch?\n\n",
  "Ein Stück Holzkohle wird auf 37000 Jahre datiert\nWie viel Prozent C14 ist noch da?\n\n",
  "Ein hölzerner Zeremonienstab weist 13 % C14 auf\nFrühere Schätzungen lagen bei 25 % – wie viele Jahre liegt das auseinander?\n\n",
  "Ein Deckbalken aus einer Grabkammer wurde mit 31 % C14 datiert\nEine moderne Untersuchung ergibt nur 17 % – wie viele Jahre wurden zu wenig berechnet?\n\n",
  "Ein in einer Höhle gefundener Holzlöffel wurde auf 22 % C14 geschätzt\nSpätere Tests ergaben 35 % – wie groß ist die Differenz in Jahren?\n\n",
  "Ein aus Ulmenholz gefertigter Schild wurde mit 39 % C14 datiert\nZuvor hatte man nur 24 % angenommen – wie viele Jahre liegt die erste Schätzung daneben?\n\n",
  "Ein in Sumpfwasser konservierter Holzbalken enthält 20 % C14\nEin Gutachten sprach zuvor von 38 % – wie alt ist der Unterschied?\n\n",
  "Ein Schwertgriff aus Lindenholz wurde mit 17 % C14 analysiert\nVorherige Methoden zeigten 30 % – wie viele Jahre beträgt die Abweichung?\n\n",
  "Ein Holzkasten aus einer römischen Villa enthält 12 % C14\nDie alte Datierung ging von 26 % aus – wie viele Jahre wurden unterschätzt?\n\n",
  "Ein eingestürzter Dachstuhl wurde mit 44 % C14 datiert\nNeuere Labormethoden ergeben nur 21 % – wie groß ist die Altersdifferenz?\n\n",
  "Ein ritueller Holzstab aus einer Grube wurde auf 32 % C14 geschätzt\nDie Korrekturanalyse ergibt 14 % – wie viele Jahre wurden falsch angegeben?\n\n",
  "Ein verkohlter Zaunpfosten zeigt 19 % C14\nFrühere Werte lagen bei 34 % – wie groß ist die zeitliche Abweichung?\n\n",
  "Ein zerfallenes Holzschild aus der Eisenzeit enthält 28 % C14\nUrsprünglich wurde 46 % angenommen – wie viele Jahre liegt das daneben?\n\n",
  "Ein mit Schnitzmustern versehener Balken wurde auf 15 % C14 datiert\nAlte Aufzeichnungen sprechen von 24 % – wie groß ist der Altersunterschied?\n\n",
  "Ein zerbrochener Pfeilschaft enthält 36 % C14\nFrühere Berichte nannten 51 % – wie viele Jahre beträgt die Differenz?\n\n",
  "Ein hölzerner Grabdeckel wurde mit 20 % C14 angegeben\nZuvor wurde ein Wert von 33 % genutzt – wie alt ist der Unterschied?\n\n",
  "Ein antiker Webrahmen enthält laut Analyse 30 % C14\nFrühere Dokumente sprachen von 43 % – wie groß ist die zeitliche Differenz?\n\n",
  "Ein Holzstab mit religiösem Symbol wurde mit 17 % C14 gemessen\nDie erste Schätzung lag bei 31 % – wie viele Jahre liegen dazwischen?\n\n",
  "Ein Spaten aus Hartholz wurde auf 13 % C14 datiert\nFrühere Berechnungen gingen von 22 % aus – wie groß ist die Differenz in Jahren?\n\n",
  "Ein zerfallenes Grabkreuz aus Holz enthält 24 % C14\nZuvor war von 40 % die Rede – wie viele Jahre wurde das Alter unterschätzt?\n\n",
  "Ein aus Walnussholz gefertigter Helmständer zeigt 26 % C14\nFrühere Ergebnisse lagen bei 39 % – wie groß ist die zeitliche Abweichung?\n\n",
];

export const questionsMixed = [
  "Ein Blattabdruck aus Vulkanasche hat 40 % C14\nAktuelle Werte liegen aber bei 18 % – wie viele Jahre liegen zwischen den Annahmen?\n\n",
  "Ein bemalter Holzteller zeigt 11 % C14\nFrüher wurden 22 % angegeben – wie viel Altersunterschied ergibt sich?\n\n",
  "Ein alter Wandteppich hat 17 % C14\nEin Katalog ging von 30 % aus – wie viele Jahre Differenz entstehen?\n\n",
  "Eine Mumie weist 13 % C14 auf\nEin alter Bericht spricht von 26 % – was ist die zeitliche Abweichung?\n\n",
  "Ein Holzstück aus einem Wrack hat 16 % C14\nEin älteres Gutachten ging von 35 % aus – wie viele Jahre trennen die Einschätzungen?\n\n",
  "Ein Blatt wurde auf 5000 Jahre datiert\nWie viel Prozent C14 enthält es heute noch?\n\n",
  "Ein Knochenfragment ist laut Analyse 12000 Jahre alt\nWie hoch ist der verbliebene C14-Anteil?\n\n",
  "Ein Stück Holz aus einer Grabkammer wurde auf 25000 Jahre geschätzt\nWelcher Prozentsatz C14 ist noch enthalten?\n\n",
  "Ein Tierknochen aus der Steppe ist 7000 Jahre alt\nWie viel Prozent C14 ist noch nachweisbar?\n\n",
  "Ein verkohlter Baumstamm wurde auf 43000 Jahre datiert\nWie viel C14 ist heute noch vorhanden?\n\n",
  "Ein Holzkeil aus einem Gletscher ist 3000 Jahre alt\nWelcher Prozentsatz C14 müsste noch vorhanden sein?\n\n",
  "Ein Papyrusfragment ist 1800 Jahre alt\nWie viel Prozent C14 bleibt nach dieser Zeit übrig?\n\n",
  "Ein organischer Stoff in einem Tonkrug wurde auf 8000 Jahre datiert\nWie viel Prozent C14 enthält er noch?\n\n",
  "Ein Stück Leder aus einer Höhle ist 16000 Jahre alt\nWie viel C14 ist noch vorhanden?\n\n",
  "Ein versteinertes Blatt ist 20000 Jahre alt\nWelcher Anteil des ursprünglichen C14 ist noch da?\n\n",
  "Ein Pfeilschaft wurde auf 9500 Jahre bestimmt\nWie viel Prozent C14 könnte man noch messen?\n\n",
  "Ein Holzstück aus einem Moor ist 6000 Jahre alt\nWelcher Prozentsatz C14 bleibt übrig?\n\n",
  "Ein Schädelknochen wurde auf 10000 Jahre datiert\nWie viel C14 dürfte noch enthalten sein?\n\n",
  "Ein gefundener Zahn ist 22000 Jahre alt\nWie viel Prozent C14 ist nachweisbar?\n\n",
  "Ein Bogen aus einem Grab wurde auf 14000 Jahre geschätzt\nWie viel Prozent C14 hat er noch?\n\n",
  "Ein Stofffetzen aus einer antiken Kleidung wurde auf 3500 Jahre datiert\nWie viel C14 ist noch enthalten?\n\n",
  "Ein Fund aus einem Seeufer ist 27000 Jahre alt\nWie viel Prozent C14 bleibt nach so langer Zeit übrig?\n\n", //hab
  "Ein Fischskelett ist 18000 Jahre alt\nWie hoch ist der verbleibende Anteil an C14?\n\n",
  "Ein Stück Kohle wird auf 2000 Jahre geschätzt\nWie viel Prozent des C14 ist noch vorhanden?\n\n",
  "Ein Baumstamm wurde mit 52000 Jahren Alter bestimmt\nWie viel C14 enthält er noch?\n\n",
  "Ein Holzwurzelrest ist 15000 Jahre alt\nWie viel Prozent C14 kann man heute noch messen?\n\n",
  "Ein Knochen ist 2500 Jahre alt\nWelcher Anteil des C14 ist noch vorhanden?\n\n",
  "Ein Tierfell in einer Höhle wurde auf 4300 Jahre geschätzt\nWie viel Prozent C14 bleibt?\n\n",
  "Ein uraltes Seil aus Hanffasern enthält 5,5% C14\nWie alt ist es?\n\n",
  "Ein gefundenes Butterstück im Moor enthält 2% C14\nWie alt ist der Fund?\n\n",
  "Ein in Sand begrabener Schildkrötenpanzer zeigt 7,7% C14\nWie alt ist er?\n\n",
  "Ein alter Holzteller enthält 11,3% C14\nBerechne sein Alter\n\n",
  "Ein Tongefäß mit organischen Rückständen zeigt 3,4% C14\nWie alt ist es?\n\n",
  "Ein in Felsnischen gelagerter Sack mit Mais enthält 8,4% C14\nWie alt ist er?\n\n",
  "Ein alter Federkopfschmuck zeigt 5,1% des ursprünglichen C14\nWie alt könnte er sein?\n\n",
  "Ein aus Moos gefertigter Schuh enthält 9,3% C14\nWie alt ist er?\n\n",
  "Ein Jagdmesser mit Holzgriff enthält 7% C14 im Griff\nBerechne das Alter\n\n",
  "Ein Gletscherfund eines Steinzeitjägers enthält 4,2% C14\nWie alt ist er?\n\n",
  "Ein Überrest eines alten Katapults enthält 6,8% C14\nWie viele Jahre sind vergangen?\n\n",
  "Ein Kornvorrat aus einem Vorratsloch zeigt 10,6% C14\nWie alt ist er?\n\n",
  "Ein aus Palmblättern gefertigter Umhang enthält 3,9% C14\nWie alt ist er?\n\n",
  "Ein in Bernstein eingeschlossenes Insekt enthält 1,4% C14\nBerechne das Alter\n\n",
  "Ein Holzstück aus einer alten Schiffsplanke zeigt 8,9% C14\nWie alt ist es?\n\n",
  "Ein gefundener Gürtel aus Bast zeigt 5,6% C14\nWie viele Jahre sind vergangen?\n\n",
  "Ein konserviertes Vogelnest enthält 2,8% C14\nWie alt ist es?\n\n",
  "Ein eingewachsener Baumzweig in einer Ruine zeigt 7,2% C14\nWie alt könnte er sein?\n\n",
  "Ein aus Gras geflochtenes Seil zeigt 6,6% C14\nWie alt ist es?\n\n",
  "Ein alter Käfig aus Bambus zeigt 11,7% C14\nBerechne das Alter\n\n",
  "Ein verrotteter Schild aus Rinde zeigt 4,3% C14\nWie alt ist er?\n\n", //hab
  "Ein Pfeilköcher aus Hirschleder zeigt 3,1% C14\nWie viele Jahre sind vergangen?\n\n",
  "Ein fragmentierter Knochen zeigt 5% C14\nWie alt könnte er sein?\n\n",
  "Ein zerbrochener Trinkbecher aus Holz enthält 12,9% C14\nWie alt ist er?\n\n",
  "Ein gewebter Teppich aus Wolle enthält 9,6% C14\nWie alt ist der Fund?\n\n",
  "Ein zerfallenes Buch aus Pflanzenfasern enthält 8% C14\nWie alt ist es?\n\n",
  "Ein Blattabdruck aus Vulkanasche hat 40 % C14\nAktuelle Werte liegen aber bei 18 % – wie viele Jahre liegen zwischen den Annahmen?\n\n",
  "Ein verzierter Holzbalken aus einem Tempel wurde auf 55 % C14 datiert\nNeuere Labormessungen ergeben nur noch 27 % – wie viele Jahre wurden übersehen?\n\n",
  "Eine in Torf konservierte Tierhaut weist 22 % C14 auf\nFrühere Analysen zeigten jedoch 38 % – wie groß ist die Differenz in Jahren?\n\n",
  "Ein aus Leinen gefertigter Gürtel wurde mit 30 % C14 geschätzt\nAktuelle Untersuchungen zeigen lediglich 11 % – um wie viele Jahre wich die erste Einschätzung ab?\n\n",
  "Ein Fragment einer antiken Holzmaske wurde ursprünglich mit 47 % C14 datiert\nNeuere Techniken belegen aber nur 19 % – wie alt ist die Lücke in Jahren?\n\n",
  "Ein Holzwagenrad aus einem Moorfund enthält laut erster Analyse 35 % C14\nDie zweite Analyse ergab lediglich 14 % – wie groß ist der Altersunterschied?\n\n",
  "Eine geschnitzte Holzfigur zeigt 41 % C14\nFrühere Berichte gingen von 60 % aus – wie viele Jahre liegen zwischen beiden Ergebnissen?\n\n",
  "Ein in Eis eingeschlossener Speer wurde auf 50 % C14 geschätzt\nNeuere Verfahren weisen 29 % nach – wie viele Jahre betrug die Fehleinschätzung?\n\n",
  "Ein Schiffsteil aus einer versunkenen Galeere enthält 25 % C14\nEin alter Bericht sprach von 44 % – wie viele Jahre trennen die beiden Werte?\n\n",
  "Ein aus Baumrinde hergestelltes Werkzeug wurde zunächst mit 33 % C14 datiert\nNeuere Untersuchungen ergaben nur 13 % – wie viele Jahre Altersunterschied ergeben sich?\n\n",
  "Eine Holztür aus einem Grabhügel wurde mit 37 % C14 bewertet\nAktuelle Messungen zeigen 18 % – wie groß ist der zeitliche Abstand?\n\n",
  "Ein durch Brand geschwärztes Holztischbein zeigt 23 % C14\nFrühere Abschätzungen lagen bei 38 % – wie alt ist der Unterschied?\n\n",
  "Ein Holzdolch aus einer keltischen Grabstätte wurde mit 48 % C14 datiert\nSpätere Analysen ergeben nur 26 % – wie viele Jahre beträgt die Differenz?\n\n",
  "Eine Bogenfragment zeigt 28 % C14\nUrsprünglich ging man von 50 % aus – wie groß ist die Differenz in Jahren?\n\n",
  "Eine Tierfalle aus Holz wurde mit 36 % C14 angegeben\nEin neuer Test zeigt jedoch nur 16 % – wie viele Jahre wurden überschätzt?\n\n",
  "Ein geschnitzter Kultgegenstand aus Tropenholz enthält 44 % C14\nEin Kollege behauptet, es seien 20 % – wie viele Jahre beträgt die Abweichung?\n\n",
  "Ein Speer mit Griff aus Mammutelfenbein wurde mit 42 % C14 datiert\nNeueste Messwerte zeigen nur 25 % – wie alt ist die Differenz?\n\n",
  "Ein in Ton eingebackenes Holzstück wurde auf 31 % C14 geschätzt\nSpäter stellte sich heraus, es sind nur 12 % – wie viele Jahre wurde das Alter überschätzt?\n\n",
  "Ein verkohlter Dachbalken zeigt 15 % C14\nZuvor ging man von 28 % aus – um wie viele Jahre wich die erste Datierung ab?\n\n",
  "Ein in Bernstein eingeschlossener Holzsplitter enthält 38 % C14\nDie erste Analyse sprach von 55 % – wie viele Jahre wurden zu wenig angenommen?\n\n",
  "Ein Webstuhlteil aus einer Grabkammer zeigt laut Analyse 18 % C14\nZuvor wurde er auf 33 % geschätzt – wie groß ist die zeitliche Lücke?\n\n",
  "Ein in einem Gletscher konserviertes Holzstück weist 26 % C14 auf\nDie erste Untersuchung ergab 40 % – wie viele Jahre liegt das auseinander?\n\n",
  "Ein Schildfragment wurde mit 43 % C14 bestimmt\nDie ursprüngliche Schätzung ging von 65 % aus – wie alt ist der Unterschied?\n\n",
  "Ein verzierter Pfeilrest wurde ursprünglich mit 20 % C14 angegeben\nNeueste Techniken zeigen nur noch 9 % – wie viele Jahre beträgt die Korrektur?\n\n",
  "Ein Grabholzpfosten zeigt 34 % C14\nUrsprünglich ging man von 48 % aus – wie groß ist die zeitliche Differenz?\n\n",
  "Ein aus Eschenholz gefertigter Wagenlenker wurde mit 30 % C14 gemessen\nVorherige Daten sagten 45 % – wie viele Jahre wurden übersehen?\n\n",
  "Ein aus Zedernholz gefertigter Dolchgriff enthält 27 % C14\nFrühere Schätzungen ergaben 41 % – wie groß ist der Altersunterschied?\n\n",
  "Ein Ritualstab aus Ahornholz wurde mit 21 % C14 analysiert\nZuvor hatte man 36 % angenommen – wie viele Jahre Differenz ergibt sich?\n\n",
  "Ein Balken einer antiken Tempelanlage zeigt 16 % C14\nDie erste Analyse ging von 28 % aus – wie groß ist die Differenz in Jahren?\n\n",
  "Ein Spinnradfragment wurde ursprünglich mit 40 % C14 eingestuft\nNeuste Messwerte liegen aber nur bei 19 % – wie alt ist die Abweichung?\n\n",
];



export const questionsEasySolutions = [
"17527.46 Jahre\n\n",
"11460.0 Jahre\n\n",
"23257.46 Jahre\n\n",
"36562.11 Jahre\n\n",
"16865.78 Jahre\n\n",
"25635.63 Jahre\n\n",
"42292.11 Jahre\n\n",
"19117.73 Jahre\n\n",
"31183.93 Jahre\n\n",
"14648.13 Jahre\n\n",
"24440.42 Jahre\n\n",
"13304.65 Jahre\n\n",
"37281.4 Jahre\n\n",
"21983.15 Jahre\n\n",
"28199.57 Jahre\n\n",
"18246.75 Jahre\n\n",
"16253.15 Jahre\n\n",
"39913.94 Jahre\n\n",
"14175.63 Jahre\n\n",
"29858.44 Jahre\n\n",
"19814.28 Jahre\n\n",
"19034.65 Jahre\n\n",
"28987.46 Jahre\n\n",
"17390.82 Jahre\n\n",
"15682.81 Jahre\n\n",
"25102.11 Jahre\n\n",
"20185.88 Jahre\n\n",
"22723.94 Jahre\n\n",
"28453.94 Jahre\n\n",
"18398.44 Jahre\n\n",
"23396.4 Jahre\n\n",
"21983.15 Jahre\n\n",
"32763.32 Jahre\n\n",
"27713.15 Jahre\n\n",
"31551.4 Jahre\n\n",
"23257.46 Jahre\n\n",
"19546.15 Jahre\n\n",
"17879.29 Jahre\n\n",
"16677.18 Jahre\n\n",
"26405.17 Jahre\n\n",
"20675.17 Jahre\n\n",
"38940.27 Jahre\n\n",
"27033.32 Jahre\n\n",
"17527.46 Jahre\n\n",
"30494.65 Jahre\n\n",
"22345.25 Jahre\n\n",
"19905.63 Jahre\n\n",
"18952.39 Jahre\n\n",
"23976.75 Jahre\n\n",
"32339.3 Jahre\n\n",
"21195.26 Jahre\n\n",
"18024.32 Jahre\n\n",
"27952.78 Jahre\n\n",
"20475.97 Jahre\n\n",
"24600.95 Jahre\n\n",
"19634.56 Jahre\n\n",
"21983.15 Jahre\n\n",
"26205.97 Jahre\n\n",
"22222.78 Jahre\n\n",
"18552.96 Jahre\n\n",
"26818.59 Jahre\n\n",
"35287.8 Jahre\n\n",
"19997.99 Jahre\n\n",
"23827.8 Jahre\n\n",
"29557.8 Jahre\n\n",
"21750.27 Jahre\n\n",
"22469.57 Jahre\n\n",
"17736.75 Jahre\n\n",
"26011.45 Jahre\n\n",
"28716.4 Jahre\n\n",
"24764.65 Jahre\n\n",
"16929.61 Jahre\n\n",
"19372.11 Jahre\n\n",
"20879.3 Jahre\n\n",
"23120.82 Jahre\n\n",
"30170.42 Jahre\n\n",
"24931.66 Jahre\n\n",
"21523.78 Jahre\n\n",
"31935.97 Jahre\n\n",
"27480.27 Jahre\n\n",
"22854.13 Jahre\n\n",
"18631.32 Jahre\n\n",
"20776.6 Jahre\n\n",
"19723.93 Jahre\n\n",
"30832.11 Jahre\n\n",
"28199.57 Jahre\n\n",
"21865.89 Jahre\n\n",
"22102.1 Jahre\n\n",
"33682.78 Jahre\n\n",
"23681.48 Jahre\n\n",
"19201.66 Jahre\n\n"
];

export const questionsHardSolutions = [
"7574.65 Jahre\n\n",
"3351.83 Jahre\n\n",
"5257.5 Jahre\n\n",
"3885.35 Jahre\n\n",
"5730.0 Jahre\n\n",
"5730.0 Jahre\n\n",
"7574.65 Jahre\n\n",
"7004.31 Jahre\n\n",
"3219.57 Jahre\n\n",
"6470.8 Jahre\n\n",
"4518.08 Jahre\n\n",
"3703.66 Jahre\n\n",
"7574.65 Jahre\n\n",
"5429.36 Jahre\n\n",
"6833.85 Jahre\n\n",
"6600.98 Jahre\n\n",
"5730.0 Jahre\n\n",
"4695.32 Jahre\n\n",
"5730.0 Jahre\n\n",
"6470.8 Jahre\n\n",
"54.62%\n\n",
"23.42%\n\n",
"4.86%\n\n",
"42.88%\n\n",
"0.55%\n\n",
"69.57%\n\n",
"80.43%\n\n",
"37.99%\n\n",
"14.44%\n\n",
"8.9%\n\n",
"31.69%\n\n",
"48.39%\n\n",
"29.83%\n\n",
"6.99%\n\n",
"18.39%\n\n",
"65.48%\n\n",
"3.82%\n\n",
"11.33%\n\n",
"78.51%\n\n",
"0.19%\n\n",
"16.29%\n\n",
"73.9%\n\n",
"59.44%\n\n",
"28.08%\n\n",
"1.14%\n\n",
"5405.78 Jahre\n\n",
"4966.38 Jahre\n\n",
"3838.25 Jahre\n\n",
"4013.52 Jahre\n\n",
"5305.98 Jahre\n\n",
"4695.32 Jahre\n\n",
"6391.68 Jahre\n\n",
"6114.57 Jahre\n\n",
"6833.85 Jahre\n\n",
"4810.54 Jahre\n\n",
"4103.86 Jahre\n\n",
"3885.35 Jahre\n\n",
"2879.33 Jahre\n\n",
"4139.73 Jahre\n\n",
"2976.01 Jahre\n\n",
"4966.38 Jahre\n\n",
"4349.03 Jahre\n\n",
"4222.81 Jahre\n\n",
"3351.84 Jahre\n\n"
];

export const questionsMixedSolutions = [
"6600.98 Jahre\n\n",
"5730.0 Jahre\n\n",
"4695.32 Jahre\n\n",
"5730.0 Jahre\n\n",
"6470.8 Jahre\n\n",
"54.62%\n\n",
"23.42%\n\n",
"4.86%\n\n",
"42.88%\n\n",
"0.55%\n\n",
"69.57%\n\n",
"80.43%\n\n",
"37.99%\n\n",
"14.44%\n\n",
"8.9%\n\n",
"31.69%\n\n",
"48.39%\n\n",
"29.83%\n\n",
"6.99%\n\n",
"18.39%\n\n",
"65.48%\n\n",
"3.82%\n\n",
"11.33%\n\n",
"78.51%\n\n",
"0.19%\n\n",
"16.29%\n\n",
"73.9%\n\n",
"59.44%\n\n",
"23976.75 Jahre\n\n",
"32339.3 Jahre\n\n",
"21195.26 Jahre\n\n",
"18024.32 Jahre\n\n",
"27952.78 Jahre\n\n",
"20475.97 Jahre\n\n",
"24600.95 Jahre\n\n",
"19634.56 Jahre\n\n",
"21983.15 Jahre\n\n",
"26205.97 Jahre\n\n",
"22222.78 Jahre\n\n",
"18552.96 Jahre\n\n",
"26818.59 Jahre\n\n",
"35287.8 Jahre\n\n",
"19997.99 Jahre\n\n",
"23827.8 Jahre\n\n",
"29557.8 Jahre\n\n",
"21750.27 Jahre\n\n",
"22469.57 Jahre\n\n",
"17736.75 Jahre\n\n",
"26011.45 Jahre\n\n",
"28716.4 Jahre\n\n",
"24764.65 Jahre\n\n",
"16929.61 Jahre\n\n",
"19372.11 Jahre\n\n",
"20879.3 Jahre\n\n",
"6600.98 Jahre\n\n",
"5881.69 Jahre\n\n",
"4518.08 Jahre\n\n",
"8293.94 Jahre\n\n",
"7487.17 Jahre\n\n",
"7574.65 Jahre\n\n",
"3147.71 Jahre\n\n",
"4503.06 Jahre\n\n",
"4673.25 Jahre\n\n",
"7700.86 Jahre\n\n",
"5956.5 Jahre\n\n",
"4150.62 Jahre\n\n",
"5068.32 Jahre\n\n",
"4793.15 Jahre\n\n",
"6703.67 Jahre\n\n",
"6517.9 Jahre\n\n",
"4288.68 Jahre\n\n",
"7845.71 Jahre\n\n",
"5159.66 Jahre\n\n",
"3056.57 Jahre\n\n",
"5010.71 Jahre\n\n",
"3561.13 Jahre\n\n",
"3415.67 Jahre\n\n",
"6600.98 Jahre\n\n",
"2850.67 Jahre\n\n",
"3351.83 Jahre\n\n",
"3453.27 Jahre\n\n",
"4455.69 Jahre\n\n",
"4626.15 Jahre\n\n",
"6154.02 Jahre\n\n",
];